# Generated by Django 2.0.7 on 2018-07-22 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='realtimeNodeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this system', primary_key=True, serialize=False)),
                ('runUser', models.IntegerField(help_text='the runUser of this system')),
                ('idleNode', models.IntegerField(help_text='the idleNode of this system')),
                ('pendJob', models.IntegerField(help_text='the pendJob of this system')),
                ('nodeName', models.CharField(help_text=' the nodeName of this system', max_length=20)),
                ('availableCore', models.IntegerField(help_text='the availableCore of this system')),
                ('nodeuprate', models.FloatField(help_text='the nodeuprate of this system')),
                ('offNode', models.IntegerField(help_text='the offNode of this system')),
                ('cpuutil', models.FloatField(help_text='the cpuutil of this system')),
                ('pendCore', models.IntegerField(help_text='the pendCore of this system')),
                ('allJob', models.IntegerField(help_text='the allJob of this system')),
                ('runJob', models.IntegerField(help_text='the runJob of this system')),
                ('occupyNode', models.IntegerField(help_text='the occupyNode of this system')),
                ('closedNode', models.IntegerField(help_text='the closedNode of this system')),
                ('allNode', models.IntegerField(help_text='the allNode of this system')),
                ('reserveNode', models.IntegerField(help_text='the reserveNode of this system')),
                ('nodeutil', models.FloatField(help_text='the nodeutil of this system')),
                ('usercount', models.IntegerField(help_text='the usercount of this system')),
                ('runCore', models.IntegerField(help_text='the runCore of this system')),
                ('penduser', models.IntegerField(help_text='the penduser of this system')),
                ('activeUser', models.IntegerField(help_text='the activeUser of this system')),
            ],
        ),
    ]
